# This file is part of Beard.
# Copyright (C) 2014 CERN.
#
# Beard is a free software; you can redistribute it and/or modify it
# under the terms of the Revised BSD License; see LICENSE file for
# more details.

language: python

matrix:
  include:
    - python: "2.7"
      env: PYTHON_VERSION="2.7" NUMPY_VERSION="1.9" SCIPY_VERSION="0.14" SKLEARN_VERSION="0.15.2"
    - python: "3.4"
      env: PYTHON_VERSION="3.4" NUMPY_VERSION="1.9" SCIPY_VERSION="0.14" SKLEARN_VERSION="0.15.2"

install: source travis-install.sh

script:
    - python setup.py install
    - py.test tests
    - pep257 beard
    - "sphinx-build -qnNW doc doc/_build/html"

after_success:
    - coveralls

notifications:
    email: false
